In [1]:
#standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## 0. An end-to-end Scikit-learn workflow

In [2]:
# 1. Get the data ready
import pandas as pd
import numpy as np
heart_disease = pd.read_csv("heart-disease.csv")

In [3]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
# Create x (feature matrix)
X = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease["target"]

In [5]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [6]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [7]:
# we can also get rid of the n_estimators warning with the code below (Not suggested)
#import warnings
#warnings.formatwarning("ignore")

In [8]:
# Fit the model to the training data (and also splitting data into training and testings)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
clf.fit(X_train, y_train); # This finds the patterns in the training data

In [10]:
# Make a prediction
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [11]:
y_test

85     1
272    0
108    1
56     1
88     1
      ..
90     1
147    1
105    1
92     1
68     1
Name: target, Length: 61, dtype: int64

In [12]:
# 4. Evaluate the model on the training data and test data
clf.score(X_train, y_train) # on training data 

1.0

In [13]:
clf.score(X_test, y_test) # on test data

0.819672131147541

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.88      0.73      0.80        30
           1       0.78      0.90      0.84        31

    accuracy                           0.82        61
   macro avg       0.83      0.82      0.82        61
weighted avg       0.83      0.82      0.82        61


In [15]:
confusion_matrix(y_test, y_preds)

array([[22,  8],
       [ 3, 28]], dtype=int64)

In [16]:
accuracy_score(y_test, y_preds)

0.819672131147541

In [17]:
# 5. Improve a model
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100:.2f}% ")
    print("")

Trying model with 10 estimators
Model accuracy on test set: 81.97% 

Trying model with 20 estimators
Model accuracy on test set: 81.97% 

Trying model with 30 estimators
Model accuracy on test set: 81.97% 

Trying model with 40 estimators
Model accuracy on test set: 81.97% 

Trying model with 50 estimators
Model accuracy on test set: 78.69% 

Trying model with 60 estimators
Model accuracy on test set: 81.97% 

Trying model with 70 estimators
Model accuracy on test set: 80.33% 

Trying model with 80 estimators
Model accuracy on test set: 81.97% 

Trying model with 90 estimators
Model accuracy on test set: 81.97% 


In [18]:
# 6. save a model and load it
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", "wb")) # "wb": write binary

In [19]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb")) # "rb": read binary
loaded_model.score(X_test,y_test)

0.819672131147541

======================================================================================================================================

## 1. Getting our data ready to be used with machine learning
Three main things we have to do:
    1. Split the data into geatures and labels (Usually `X` & `y`)
    2. Fillint (also called imputing) or (disregarding missing values)
    3. Converting nun numerical to numercial values (also called featureing coding)

In [20]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [21]:
X = heart_disease.drop("target", axis=1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [22]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [23]:
## Split data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [24]:
X_train.shape, X_test.shape, y_train.shape, y_test

((242, 13),
 (61, 13),
 (242,),
 186    0
 101    1
 131    1
 129    1
 106    1
       ..
 198    0
 242    0
 24     1
 275    0
 235    0
 Name: target, Length: 61, dtype: int64)

In [25]:
X.shape[0] * 0.8

242.4

In [26]:
len(heart_disease)

303

In [27]:
242 + 61

303

### 1.1 Make sure it's all numercial

In [28]:
car_sales = pd.read_csv("new_datas/car-sales-extended.csv")

In [29]:
car_sales

Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [30]:
len(car_sales)

1000

In [31]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [32]:
# Split the data into X, y
X = car_sales.drop("Price", axis=1)
y = car_sales["Price"]

# split into training and test set
x_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [33]:
# Build machine learning model
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: Found input variables with inconsistent numbers of samples: [242, 800]

In [34]:
# turn the categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"] # Why doors? cause we need to categorize the cars based on the number of the doors as well and this is the list of stuff we want to transform
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hoe",
                                   one_hot,
                                   categorical_features)],remainder="passthrough")
transformed_X = transformer.fit_transform(X)
transformed_X

transformed_X = pd.DataFrame(transformed_X,)
transformed_X

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [35]:
dummies = pd.get_dummies(car_sales[["Make", "Colour","Doors"]]).astype(int)
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [36]:
# Let's refit te model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, y, test_size=0.2)

model.fit(X_train, y_train)

RandomForestRegressor()

In [37]:
model.score(X_test, y_test)

0.3235867221569877

## 1.2 What if there were missing values?
1. Fill them with some values (also known as imputation)
2. Remove the samples with missing data altogether

In [38]:
car_sales_missing = pd.read_csv("new_datas/car-sales-extended-missing-data.csv")
car_sales_missing

Make Colour  Odometer (KM)  Doors    Price
0     Honda  White        35431.0    4.0  15323.0
1       BMW   Blue       192714.0    5.0  19943.0
2     Honda  White        84714.0    4.0  28343.0
3    Toyota  White       154365.0    4.0  13434.0
4    Nissan   Blue       181577.0    3.0  14043.0
..      ...    ...            ...    ...      ...
995  Toyota  Black        35820.0    4.0  32042.0
996     NaN  White       155144.0    3.0   5716.0
997  Nissan   Blue        66604.0    4.0  31570.0
998   Honda  White       215883.0    4.0   4001.0
999  Toyota   Blue       248360.0    4.0  12732.0

[1000 rows x 5 columns]

In [39]:
car_sales_missing.isna().sum() # seeing how many missing values are there

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [40]:
# Create X and y:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [41]:
# Let's try to convert the data into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot = OneHotEncoder()

categorical_features = ["Make", "Colour", "Doors"]

transformer = ColumnTransformer([("One_hot", one_hot, categorical_features)], remainder="passthrough") 

transformed_X = pd.DataFrame(transformer.fit_transform(X))
transformed_X

0
0      (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
1      (0, 0)\t1.0\n  (0, 6)\t1.0\n  (0, 13)\t1.0\n...
2      (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
3      (0, 3)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
4      (0, 2)\t1.0\n  (0, 6)\t1.0\n  (0, 11)\t1.0\n...
..                                                 ...
995    (0, 3)\t1.0\n  (0, 5)\t1.0\n  (0, 12)\t1.0\n...
996    (0, 4)\t1.0\n  (0, 9)\t1.0\n  (0, 11)\t1.0\n...
997    (0, 2)\t1.0\n  (0, 6)\t1.0\n  (0, 12)\t1.0\n...
998    (0, 1)\t1.0\n  (0, 9)\t1.0\n  (0, 12)\t1.0\n...
999    (0, 3)\t1.0\n  (0, 6)\t1.0\n  (0, 12)\t1.0\n...

[1000 rows x 1 columns]

### Option 1 : Fill missing data with Pandas

In [42]:
car_sales_missing = pd.read_csv("new_datas/car-sales-extended-missing-data.csv")

In [43]:
# Fill the "Make" column
car_sales_missing["Make"].fillna("missing", inplace=True)

# Fill the "Colur" column
car_sales_missing["Colour"].fillna("missing", inplace=True)

# Fill the "Odometer (KM)" column
car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace = True)

# Fill the "Doors" column
car_sales_missing["Doors"].fillna(4, inplace=True)


In [44]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [45]:
# Remove the Rows with missing the price values
car_sales_missing.dropna(inplace=True)

In [46]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [47]:
len(car_sales_missing)

950

In [48]:
# Create X and y:
X = car_sales_missing.drop("Price", axis=1)
y = car_sales_missing["Price"]

In [49]:
# Let's try to convert the data into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot = OneHotEncoder()

categorical_features = ["Make", "Colour", "Doors"]

transformer = ColumnTransformer([("One_hot", one_hot, categorical_features)], remainder="passthrough") 

transformed_X = transformer.fit_transform(X)
transformed_X = pd.DataFrame.sparse.from_spmatrix(transformed_X)
transformed_X

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
947  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14  
0     35431.0  
1    192714.0  
2     84714.0  
3    154365.0  
4    181577.0  
..        ...  
945   35820.0  
946  155144.0  
947   66604.0  
948  215883.0  
949  248360.0  

[950 rows x 15 columns]

### option 2: Fill the missing values with Scikit-learn

In [50]:
car_sales_missing = pd.read_csv("new_datas/car-sales-extended-missing-data.csv")

In [51]:
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [52]:
car_sales_missing.dropna(subset=["Price"], inplace=True) # this'll delete all the rows that has nan in price columns
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [53]:
# Split into X and y
X = car_sales_missing.drop("Price", axis = 1)
y = car_sales_missing["Price"]


In [54]:
# Fill the missing values with scikit-learn
from sklearn.impute import SimpleImputer # Imputers fill the missing data
from sklearn.compose import ColumnTransformer

# Fit categorical values with "Misiing" & numerical values with mean

car_imputer = SimpleImputer(strategy="constant", fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

# Define columns
car_features = ["Make", "Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Create an imputer (sth that dills missing data)

imputer = ColumnTransformer([("car_imputer", car_imputer, car_features),
                             ("door_imputer", door_imputer, door_features),
                             ("num_imputer", num_imputer, num_features)])

# Transform the data 
filled_X = imputer.fit_transform(X)
filled_X

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [55]:
car_sales_filled = pd.DataFrame(filled_X,
                                columns=["Make", "Colour", "Doors", "Odometer (KM)"])
car_sales_filled.head()

Make Colour Doors Odometer (KM)
0   Honda  White   4.0       35431.0
1     BMW   Blue   5.0      192714.0
2   Honda  White   4.0       84714.0
3  Toyota  White   4.0      154365.0
4  Nissan   Blue   3.0      181577.0

In [56]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [57]:
X_train, X_test, y_train, y_test = train_test_split(filled_X, y, test_size=0.2)

In [58]:
# Let's try to convert the data into numeric data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

one_hot = OneHotEncoder()

categorical_features = ["Make", "Colour", "Doors"]

transformer = ColumnTransformer([("One_hot", one_hot, categorical_features)], remainder="passthrough") 

transformed_X = pd.DataFrame.sparse.from_spmatrix((transformer.fit_transform(car_sales_filled)))
transformed_X

0    1    2    3    4    5    6    7    8    9    10   11   12   13  \
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1    1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
4    0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
945  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
946  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0   
947  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
948  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
949  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

           14  
0     35431.0  
1    192714.0  
2     84714.0  
3    154365.0  
4    181577.0  
..        ...  
945   35820.0  
946  155144.0  
947   66604.0  
948  215883.0  
949  248360.0  

[950 rows x 15 columns]

In [59]:
# Now we got our data as numbers and filled (No missing values)
# Let's fill a model
np.random.seed(42)
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)

In [60]:
y_test

203    10547.0
979    17940.0
729    12950.0
838     5905.0
919     9826.0
        ...   
625    10377.0
33      9780.0
31      6866.0
746    16705.0
305    18375.0
Name: Price, Length: 190, dtype: float64

In [61]:
model = RandomForestRegressor()
model.fit(X_train,y_train)
model.score(X_test, y_test)

0.21990196728583944

In [62]:
len(car_sales_filled), len(car_sales)

(950, 1000)

 ## Choosing the right stimator/algorithm for your problem
Some things to note:
* Sklearn refers to machine learning models, algorithm as estimators
* Classification problem = predicting a category (heart disease or not)
    * Sometimes you'll see `clf` (short for classifier) used as a classification estimator'
* Regression problem - predicting a number (selling price of a car)

If you're working on a machine learning problem and looking to use sklearn and not sure what model to use, refer to the sklearn machine learning map:
https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

### 2.1 Picking a machine learning midel for a regression problem
Let's use the California Housing dataset' (Toy dataset of sklearn)
link: https://scikit-learn.org/stable/datasets/toy_dataset.html

In [63]:
# Get California Housing dataset
from sklearn.datasets import fetch_california_housing

In [64]:
housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [65]:
housing_df = pd.DataFrame(housing["data"], columns=housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [66]:
housing_df["MedHousVal"] = housing["target"]

In [67]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHousVal  
0    -122.23       4.526  
1    -122.22       3.585  
2    -122.24       3.521  
3    -122.25       3.413  
4    -122.25       3.422

In [68]:
# Import algorithm/estimators
from sklearn.linear_model import Ridge

# Set up random seed
np.random.seed(42)

# Create the data
X = housing_df.drop("MedHousVal", axis= 1)
y = housing_df["MedHousVal"] # medium house price in $100,000s

# split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Insetentieate and fit the model (on the training set)
# you have to study the model selection document to get a better undrestanding of what's the best model for you... in this question the linear model looks OK!
model  = Ridge()
model.fit(X_train, y_train)

# Check the score model (on the test set)
model.score(X_train, y_train), model.score(X_test, y_test)

(0.6125511245209703, 0.5758549611440126)

In [69]:
y_preds = model.predict(X)
y_preds

array([4.15177567, 3.9991897 , 3.67392492, ..., 0.15164169, 0.30622806,
       0.50972872])

 What if `Ridge` didn't work or the score didn't fit our needs?
Well we can always try a different model
How about we try an Ensemble modeL? (An ensemble id a combination of smaller models to try and make better predictions than just a single model)

Sklearn Ensemble models can be found here:
https://scikit-learn.org/stable/modules/ensemble.html

In [70]:
# Import the algorithm
from sklearn.ensemble import RandomForestRegressor
model_rfr = RandomForestRegressor(n_estimators=100)

# Set a seed
np.random.seed(40)

# Create the data set
X = housing_df.drop("MedHousVal", axis= 1)
y = housing_df["MedHousVal"] # medium house price in $100,000s

# split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Fit the model
model_rfr.fit(X_train, y_train)

# Check the score
model_rfr.score(X_train, y_train), model_rfr.score(X_test, y_test)

(0.9726480650801225, 0.8006294256979274)

In [71]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHousVal, Length: 20640, dtype: float64

In [72]:
y_preds_rfr = model_rfr.predict(X)
y_preds_rfr

array([4.3430504, 3.7128006, 3.9566909, ..., 0.78378  , 0.84099  ,
       0.97404  ])

In [73]:
housing_df.MedHousVal

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHousVal, Length: 20640, dtype: float64

In [74]:
def best_n_estimator(X, y, min=100, max=150, jump=10):
    """  
    X = X labeled data
    y = y labeled data
    min = min number of estimators (default = 100)
    max = max number of estimators (default = 150)
    jump = the increment from min to max (default = 10)
    """
    np.random.seed(42)
    
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    for i in range(min, max + 1, jump):
        print(f"Checking with {i} estimators")
        model = RandomForestRegressor(n_estimators=i).fit(X_train, y_train)
        print(f"The score of the model with {i} estimators is {model.score(X_test, y_test) * 100:.2f}%\n")


### 2.2 Picking a mahcine learning model for classification problem


In [75]:
heart_disease = pd.read_csv("new_datas/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [76]:
len(heart_disease)

303

In [77]:
# Consulting the map and it says try LinearSVC
# Trying a linearSVC
from sklearn.svm import LinearSVC

# Seup random seed
np.random.seed(42)

# Make a data
X = heart_disease.drop("target", axis =1 )
y = heart_disease["target"]

# Split the data to test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

# Model the and fit the data
model = LinearSVC(max_iter=10000)
model.fit(X_train, y_train)


model.score(X_train, y_train), model.score(X_test, y_test)

C:\Users\Pouya\Desktop\ml\env\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\Pouya\Desktop\ml\env\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


(0.743801652892562, 0.8688524590163934)

In [78]:
heart_disease["target"].value_counts()

# In case not working: we have to consult the model Cheat sheet again
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make a data
X = heart_disease.drop("target", axis =1 )
y = heart_disease["target"]

# Split the data to test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

# Model and fit the data
model = RandomForestClassifier()
model.fit(X_train, y_train)

model.score(X_train, y_train), model.score(X_test, y_test)

(1.0, 0.8524590163934426)

Tibdit:

    1. if you have structured data, use ensemble methods
    2. if you have unstructured data, use Deep learning or transfer learning  

In [79]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

# 3. Fit the model/algorithm on our data and use it ti make predictions 
### 3.1 Fitting a model to the data

Different names for
X = features, feature variables, data
y = labels, targets, target variables

In [80]:
# In case not working: we have to consult the model cheet sheet again
from sklearn.ensemble import RandomForestClassifier

# Setup random seed
np.random.seed(42)

# Make a data
X = heart_disease.drop("target", axis =1 )
y = heart_disease["target"]

# Split the data to test and train
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

# Create the model
model = RandomForestClassifier()

# Fit the model to the data
model.fit(X_train, y_train)

# Evaluate the model
model.score(X_train, y_train), model.score(X_test, y_test)

(1.0, 0.8524590163934426)

### 3.2 Make a prediction using a mache learning model

#### Use a trained model to make predictions
2 ways to make predictions
1. `predict()`
2. `predict_proba()`

In [81]:
# Use a trained model to make a prediction
model.predict(np.array([1, 7, 8, 3, 4]).reshape(5, 1)) # This doesn't work

C:\Users\Pouya\Desktop\ml\env\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: X has 1 features, but RandomForestClassifier is expecting 13 features as input.

In [82]:
model.predict(X_test)

np.array(y_test)

# Compare predictions to truth labels to evaluate the model
y_preds = model.predict(X_test)
np.mean(y_preds == y_test)

0.8524590163934426

In [83]:
model.score(X_test, y_test)

0.8524590163934426

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8524590163934426

 Make predictions with predict_proba() 


In [85]:
# Predict_proba returns probabiliteis of a *classification label
model.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [86]:
# Let's predict() on the same data
model.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

`Predict()` can also be used for regression models.

In [87]:
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHousVal  
0    -122.23       4.526  
1    -122.22       3.585  
2    -122.24       3.521  
3    -122.25       3.413  
4    -122.25       3.422

In [88]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Create the data:
X = housing_df.drop("MedHousVal", axis=1)
y = housing_df["MedHousVal"]

# Split the data 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Make the model
model = RandomForestRegressor()

# Fit the model
model.fit(X_train, y_train)

# Make predictions on the test data set
y_preds = model.predict(X_test)

In [89]:
y_preds[:10] 

array([0.49384  , 0.75494  , 4.9285964, 2.54316  , 2.33176  , 1.6525301,
       2.34323  , 1.66182  , 2.47489  , 4.8344779])

In [90]:
np.array(y_test[:10])

array([0.477  , 0.458  , 5.00001, 2.186  , 2.78   , 1.587  , 1.982  ,
       1.575  , 3.4    , 4.466  ])

In [91]:
len(y_preds), len(y_test)

(4128, 4128)

In [92]:
# Compare the predictions to the truth
from sklearn.metrics import mean_absolute_error, mean_squared_error
mean_absolute_error(y_test, y_preds), mean_squared_error(y_test, y_preds)

(0.32659871732073664, 0.2534678520824551)

In [93]:
housing_df["MedHousVal"]

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: MedHousVal, Length: 20640, dtype: float64

## 4. Evaluating a machine learning model

Three ways to evaluate Scikit-learn models/estimators
1. Estimator's built-in `score()` method
2. The `scoring` parameter
3. Peoblem-specific metric functions

You can read more on scikit-lean website

### 4.1 Evaluating a model with the score method

In [94]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

# Creating X-y
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create and fit the data into the model
model = RandomForestClassifier()

model.fit(X_train, y_train)


RandomForestClassifier()

In [95]:
# Highest value for the score() is 1.0 and the lowest is 0.0 
model.score(X_train, y_train)

1.0

In [96]:
model.score(X_test, y_test)

0.8524590163934426

In [97]:
model.predict_proba(X_train[:10])

array([[0.01, 0.99],
       [0.88, 0.12],
       [0.81, 0.19],
       [0.03, 0.97],
       [0.93, 0.07],
       [0.24, 0.76],
       [0.1 , 0.9 ],
       [0.03, 0.97],
       [0.69, 0.31],
       [0.05, 0.95]])

Let's use the `score` on our regression problem...

In [98]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

# Creating X-y
X = housing_df.drop("MedHousVal", axis=1)
y = housing_df["MedHousVal"]

# Split the data to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create the model
model = RandomForestRegressor(n_estimators=100)

# Fit the model
model.fit(X_train, y_train)

# Evaluate the model
model.score(X_train, y_train), model.score(X_test, y_test)

(0.9736801960414609, 0.8065734772187598)

+ The default score() evaluation metric is r_squared for regression algorithms
+ Highest = 1.0, Lowest = 0.0

In [99]:
y_test.mean()

2.0550030959302323

In [100]:
y_test

20046    0.47700
3024     0.45800
15663    5.00001
20484    2.18600
9814     2.78000
          ...   
15362    2.63300
16623    2.66800
18086    5.00001
2144     0.72300
3665     1.51500
Name: MedHousVal, Length: 4128, dtype: float64

### 4.2 Evaluating a model using the scoring parameter


In [101]:
from sklearn.model_selection import cross_val_score

In [102]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

# Creating X-y
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Split the data to train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create and fit the data into the model
model = RandomForestClassifier()

model.fit(X_train, y_train);

In [103]:
model.score(X_test, y_test)

0.8524590163934426

In [104]:
cross_val_score(model, X, y, cv= 10)

array([0.90322581, 0.80645161, 0.87096774, 0.9       , 0.86666667,
       0.76666667, 0.7       , 0.83333333, 0.73333333, 0.8       ])

In [105]:
np.random.seed(42)

# Single training and test split score
model_single_score = model.score(X_test,y_test)

# Take mean of 5-fold cross-validation score
model_cross_val_score = np.mean(cross_val_score(model, X, y, cv=5))

# Compare the two
model_single_score, model_cross_val_score

(0.8524590163934426, 0.8248087431693989)

In [106]:
# Default scoring parameter of classifier = mean accuracy
model.score()

TypeError: ClassifierMixin.score() missing 2 required positional arguments: 'X' and 'y'

In [ ]:
# Scoring parameter set to None bt default
cross_val_score(model, X, y, cv=5, scoring=None)

### 4.2.1 Classification model evaluation metrics

1. Accuract
2. Area under ROC curve
3. Confusion metrix
4. Classification report

**Accuracy**

In [ ]:
heart_disease.head()

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis =1)
y = heart_disease["target"]

clf = RandomForestClassifier()
cross_val_score = cross_val_score(clf, X, y, cv = 5)

In [ ]:
np.mean(cross_val_score)

In [ ]:
print(f"Heart Disease Classifier Accuracy: {np.mean(cross_val_score) * 100:.2f}%")

**Area under the receiver operating characteristic curve (AUC/ROC)**

* Area under curve (AUC)
* ROC curve

ROC curves are a comparison of a model's True positive rate (tpr) versus a model false positive rate (fpr).
* True positive = model predicts 1 when truth is 1
* False positive = model predicts 1 when truth is 0
* True negative = model predicts 0 when truth is 0
* False negative = model predicts 0 when truth is 1

In [ ]:
# Create X_test ... etc
np.random.seed(42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.metrics import roc_curve

# Fit the clssifier
clf.fit(X_train, y_train)

# Make predictions whith probabilities 
y_probs = clf.predict_proba(X_test)

y_probs[:10], len(y_probs)

In [ ]:
y_probs_positive = y_probs[:, 1]
y_probs_positive[:10]

In [ ]:
# Calculate fpr, tpr and thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_probs_positive)

# Check the false positive rates
fpr

In [ ]:
# Create a finction for plotting ROC curves
import matplotlib.pyplot as plt

def plot_roc_curve(fpr, tpr):
    """
    Plots a ROC curve given the false positive rate (fpr)
    and true positive rate (tpr)
    """
    #  Plot roc curve
    plt.plot(fpr, tpr, color="orange", label="ROC")

    # Plot line with no predctive power (baseline)
    plt.plot([0,1], [0,1], color="darkblue", linestyle="--", label="Guessing")

    # Customize the plot
    plt.xlabel ("False positive rate (fpr)")
    plt.ylabel ("True positive rate (tpr)")
    plt.title("Reciver Operating Characteristiv (ROC) Curve")
    plt.legend()
    plt.show()


plot_roc_curve(fpr, tpr)

In [ ]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_probs_positive)

In [ ]:
# Plot perfect ROC curve and AUC score
fpr, tpr, thresholds = roc_curve(y_test, y_test)
plot_roc_curve(fpr, tpr)

In [ ]:
tpr, fpr

In [ ]:
# Perfect AUC score
roc_auc_score(y_test, y_test)

**Confusion Matrix**


A confusion matrix is a quick way to compare the labels a model predicts and the actual labels it was supposed to predict.

In essence, giving a an idea of where the model is getting confused

In [ ]:
from sklearn.metrics import confusion_matrix

y_preds = clf.predict(X_test)

confusion_matrix(y_test, y_preds)

In [ ]:
# Visulize confusion matrix with pd.crosstab()
pd.crosstab(y_test, y_preds, rownames=["Actual Labesl"], colnames=["Predicted labels"])

In [ ]:
22 + 7 + 8 + 24 == len(y_preds), len(y_preds), 22 + 7 + 8 + 24

In [ ]:
# Make our confusion matrix more visual with Seaborn's heatmap()
import seaborn as sns

# Set the font scale for seaborn
sns.set(font_scale= 1.5)
 
# Plot it using seaborn
sns.heatmap(conf_mat);

**Classification Report**

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_preds))